# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# coding: utf-8

#Grade.create(year: '1回生')
#Grade.create(year: '2回生')
#Grade.create(year: '3回生')
#Grade.create(year: '4回生')

#Department.create(name: '経済学部')
#Department.create(name: '理工学部')
#Department.create(name: 'スポーツ健康科学部')
#Department.create(name: '食マネジメント学部')
#Department.create(name: '情報理工学部')
#Department.create(name: '生命科学部')
#Department.create(name: '薬学部')

#Subject.create(name: '経済学科')
#Subject.create(name: '理工学科')
#Subject.create(name: '数理科学科')
#Subject.create(name: '物理科学科')
#Subject.create(name: '電気電子工学科')
#Subject.create(name: '電子情報工学科')
#Subject.create(name: '機械工学科')
#Subject.create(name: 'ロボティクス学科')
#Subject.create(name: '都市システム工学科')
#Subject.create(name: '環境システム工学科')
#Subject.create(name: '建築都市デザイン学科')
#Subject.create(name: 'スポーツ健康科学科')
#Subject.create(name: '食マネジメント学科')
#Subject.create(name: '情報理工学科')
#Subject.create(name: '生命科学科')
#Subject.create(name: '応用化学科')
#Subject.create(name: '生物工学科')
#Subject.create(name: '生命情報学科')
#Subject.create(name: '生命医科学科')
#Subject.create(name: '薬学科')
#Subject.create(name: '創薬科学科')

#教養
#Lesson.create(name: '哲学と人間')
#Lesson.create(name: '人間性と倫理')
#Lesson.create(name: '心理学入門')
#Lesson.create(name: '論理と思考')
#Lesson.create(name: '科学技術と倫理')
#Lesson.create(name: 'ジェンダー論')
#Lesson.create(name: '社会学入門')
#Lesson.create(name: '文化人類学入門')
#Lesson.create(name: '文学と社会')
#Lesson.create(name: '現代の教育')
#Lesson.create(name: 'その他')
#Lesson.create(name: '世界の言語と文化')
#Lesson.create(name: '映像と表現')
#Lesson.create(name: '現代社会と法')
#Lesson.create(name: '市民と政治')
#Lesson.create(name: '日本国憲法')
#Lesson.create(name: '国際化と法')
#Lesson.create(name: '現代日本の政治')
#Lesson.create(name: '現代の国際関係と日本')
#Lesson.create(name: '歴史観の形成')
#Lesson.create(name: 'エリアスタディ入門')
#Lesson.create(name: '新しい日本史像')
#Lesson.create(name: '中国の国家と社会')
#Lesson.create(name: '東アジアと朝鮮半島')
#Lesson.create(name: '科学的な見方・考え方')
#Lesson.create(name: '宇宙科学')
#Lesson.create(name: '地球科学')
#Lesson.create(name: '生命科学（分子と生命）')
#Lesson.create(name: '生命科学（生物と生態系)')
#Lesson.create(name: '数理の世界')
#Lesson.create(name: '情報の数理')
#Lesson.create(name: '情報科学')
#Lesson.create(name: '情報技術と社会')
#Lesson.create(name: '平和学入門')
#Lesson.create(name: '現代の人権')
#Lesson.create(name: '日本の近現代と立命館')
#Lesson.create(name: '戦争の歴史と現在')
#Lesson.create(name: '国際平和交流セミナー')
#Lesson.create(name: '地域参加学習入門')
#Lesson.create(name: '現代社会のフィールドワーク')
#Lesson.create(name: '学びとキャリア')
#Lesson.create(name: 'シチズンシップ・スタディーズⅡ')
#Lesson.create(name: 'スポーツの歴史と発展')
#Lesson.create(name: 'スポーツと現代社会')
#Lesson.create(name: 'スポーツのサイエンス')
#Lesson.create(name: '現代人とヘルスケア')
#Lesson.create(name: 'スポーツ方法実習Ⅰ')
#Lesson.create(name: '宗教と社会')
#Lesson.create(name: 'メンタルヘルス')
#Lesson.create(name: '（留）日本の文化・地理・歴史')
#Lesson.create(name: '美と芸術の論理')
#Lesson.create(name: 'メディアと現代文化')
#Lesson.create(name: '観光学')
#Lesson.create(name: '京都学')
#Lesson.create(name: '（留）日本語学')
#Lesson.create(name: '社会と福祉')
#Lesson.create(name: '災害と安全')
#Lesson.create(name: '（留）日本の社会・政治')
#Lesson.create(name: '（留）日本の経済・経営')
#Lesson.create(name: 'ヨーロッパの歴史')
#Lesson.create(name: 'アメリカの歴史')
#Lesson.create(name: 'イスラーム世界の多様性')
#Lesson.create(name: '現代環境論')
#Lesson.create(name: '科学と技術の歴史')
#Lesson.create(name: '生命科学と倫理')
#Lesson.create(name: '科学・技術と社会')
#Lesson.create(name: '現代の科学技術')
#Lesson.create(name: '（留）日本の自然・科学技術')
#Lesson.create(name: 'ソーシャルコラボレーション演習')
#Lesson.create(name: '仕事とキャリア')
#Lesson.create(name: 'コーオプ教育概論')
#Lesson.create(name: '社会とキャリア')
#Lesson.create(name: 'スポーツ方法実習II')

# 専門
#Lesson.create(name: '経済学入門')
#Lesson.create(name: 'ミクロ経済学Ⅰ')
#Lesson.create(name: 'ミクロ経済学Ⅱ')
#Lesson.create(name: '社会経済学中級α')
#Lesson.create(name: '社会経済学中級β')
#Lesson.create(name: 'マクロ経済学Ⅰ')
#Lesson.create(name: 'マクロ経済学Ⅱ')
#Lesson.create(name: '分析ツール／経済数学Ⅰ')
#Lesson.create(name: '情報処理演習')
#Lesson.create(name: '経済数学Ⅰ')
#Lesson.create(name: '経済数学Ⅱ')
#Lesson.create(name: '経済数学Ⅲ')
#Lesson.create(name: '経済数学Ⅳ')
#Lesson.create(name: '情報処理Ⅰ')
#Lesson.create(name: '情報処理Ⅱ')
#Lesson.create(name: '経済史入門')
#Lesson.create(name: '簿記入門Ⅰ')
#Lesson.create(name: '簿記入門Ⅱ')
#Lesson.create(name: 'キャリアデザイン')
#Lesson.create(name: '日本経済史Ⅰ')
#Lesson.create(name: '日本経済史Ⅱ')
#Lesson.create(name: '計量経済学Ⅰ')
#Lesson.create(name: '西洋経済史Ⅰ')
#Lesson.create(name: '財政学')
#Lesson.create(name: '計量経済学Ⅱ')
#Lesson.create(name: '金融論')
#Lesson.create(name: '経済学史')
#Lesson.create(name: '経済統計Ⅰ')
#Lesson.create(name: '社会調査入門')
#Lesson.create(name: '日本経済論')
#Lesson.create(name: '国際経済学')
#Lesson.create(name: '民法Ⅰ')
#Lesson.create(name: '民法Ⅱ')
#Lesson.create(name: 'マネジメント論')
#Lesson.create(name: 'マーケティング論')
#Lesson.create(name: '企業論')
#Lesson.create(name: '会計学')
#Lesson.create(name: '東洋経済史Ⅰ')
#Lesson.create(name: '西洋経済史Ⅱ')
#Lesson.create(name: '東洋経済史Ⅱ')
#Lesson.create(name: '国際貿易論')
#Lesson.create(name: '社会政策')
#Lesson.create(name: '国際金融論')
#Lesson.create(name: '社会思想史')
#Lesson.create(name: '経済統計Ⅱ')
#Lesson.create(name: '経済変動論')
#Lesson.create(name: '貨幣・信用論')
#Lesson.create(name: '会社法')
#Lesson.create(name: '労働法')
#Lesson.create(name: '経済法')
#Lesson.create(name: '税法')
#Lesson.create(name: '商法')
#Lesson.create(name: '国際法')
#Lesson.create(name: '行政法')

#経済戦略コース
#Lesson.create(name: '経済戦略論Ⅰ')
#Lesson.create(name: '経済戦略論Ⅱ')
#Lesson.create(name: '公共経済学')
#Lesson.create(name: '組織と制度の経済学')
#Lesson.create(name: '金融政策論')
#Lesson.create(name: '地方財政論')
#Lesson.create(name: '産業組織論')
#Lesson.create(name: 'ゲーム理論')
#Lesson.create(name: '環境経済学1')
#Lesson.create(name: '地域経済論')
#Lesson.create(name: '数理経済学Ⅰ')
#Lesson.create(name: '数理経済学Ⅱ')
#Lesson.create(name: '企業と雇用システム')
#Lesson.create(name: '情報経済論')
#Lesson.create(name: 'マクロエコノミック・ダイナミクス')
#Lesson.create(name: 'オープンマクロ経済学')
#Lesson.create(name: '経済戦略特殊講義')

# ヒューマ ン・エコノミーコー ス
#Lesson.create(name: 'ヒューマン・エコノミー論Ⅰ ')
#Lesson.create(name: 'ヒューマン・エコノミー論Ⅱ')
#Lesson.create(name: '生活経済論')
#Lesson.create(name: '福祉経済論')
#Lesson.create(name: '労働経済論')
#Lesson.create(name: 'サービス経済論')
#Lesson.create(name: '観光経済論')
#Lesson.create(name: '環境経済学1')
#Lesson.create(name: '食糧経済論')
#Lesson.create(name: '保険経済論')
#Lesson.create(name: '地域経済論')
#Lesson.create(name: 'ヒューマン・エコノミー特殊講義')
#Lesson.create(name: '医療経済論')
#Lesson.create(name: '平和の経済学')
#Lesson.create(name: '地域福祉論')
#Lesson.create(name: '文化経済学')

#金融経済コース
#Lesson.create(name: '金融経済入門')
#Lesson.create(name: '証券投資論')
#Lesson.create(name: '金融市場分析実習Ⅰ')
#Lesson.create(name: '金融政策論')
#Lesson.create(name: '金融法')
#Lesson.create(name: '財務諸表論')
#Lesson.create(name: 'リスク管理論')
#Lesson.create(name: 'フィナンシャルエコノミクス')
#Lesson.create(name: '保険経済論')
#Lesson.create(name: '企業税務論')
#Lesson.create(name: 'オープンマクロ経済学')
#Lesson.create(name: '行動経済学')
#Lesson.create(name: '金融市場分析実習Ⅱ・Ⅲ')
#Lesson.create(name: '金融経済特殊講義')

#環境・都市地域コース
#Lesson.create(name: '環境・地域経済論')
#Lesson.create(name: '環境科学')
#Lesson.create(name: '環境・都市地域特殊講義Ⅰ')
#Lesson.create(name: '環境法')
#Lesson.create(name: '環境経済評価論')
#Lesson.create(name: '環境・開発論')
#Lesson.create(name: '環境経営論')
#Lesson.create(name: '食糧経済論')
#Lesson.create(name: '環境経済学1')
#Lesson.create(name: '環境経済学2')
#Lesson.create(name: '農業経済論')
#Lesson.create(name: '地方財政論')
#Lesson.create(name: '地域経済論')
#Lesson.create(name: '環境指標')
#Lesson.create(name: '環境評価システム')
#Lesson.create(name: '都市・地域マネジメント')
#Lesson.create(name: '都市・地域マネジメント演習')
#Lesson.create(name: '環境・都市地域特殊講義Ⅱ')

#国債経済学科科目
#Lesson.create(name: '国際金融市場論')
#Lesson.create(name: '比較経済論')
#Lesson.create(name: 'アメリカ経済論')
#Lesson.create(name: 'アジア経済論')
#Lesson.create(name: '国際技術移転論')
#Lesson.create(name: '国際取引法')
#Lesson.create(name: 'EU経済論')
#Lesson.create(name: '中国経済論')
#Lesson.create(name: '多国籍企業論')
#Lesson.create(name: '国際経済協力論')
#Lesson.create(name: 'ロシア経済論')
#Lesson.create(name: 'エリアスタディ特殊講義')
#Lesson.create(name: 'ODA・国際援助論')
#Lesson.create(name: '環境・開発論')
#Lesson.create(name: '途上国経済論')
#Lesson.create(name: '開発経済学')
#Lesson.create(name: '国際経済機構論')
#Lesson.create(name: '開発教育論')
#Lesson.create(name: '国際経済特殊講義')

#特殊講義
#Lesson.create(name: 'Economics')

#経済学部
#Teacher.create(name: '我妻伸彦')
#Teacher.create(name: '稲澤 泉')
#Teacher.create(name: '上田 眞理砂')
#Teacher.create(name: '大川 隆夫')
#Teacher.create(name: '大川 昌幸')
#Teacher.create(name: '金丸 裕一')
#Teacher.create(name: '河音 琢郎')
#Teacher.create(name: '河村 ミッシェル')
#Teacher.create(name: '紀國 洋')
#Teacher.create(name: '久保 壽彦')
#Teacher.create(name: 'その他')
#Teacher.create(name: '黒川 清登')
#Teacher.create(name: 'GRAEWE GUDRUN')
#Teacher.create(name: '後閑 洋一')
#Teacher.create(name: '言美 伊知朗')
#Teacher.create(name: '佐藤 隆')
#Teacher.create(name: '佐藤 卓利')
#Teacher.create(name: '四方 利明')
#Teacher.create(name: '島田 幸司')
#Teacher.create(name: '杉田 伸樹')
#Teacher.create(name: '曹 瑞林')
#Teacher.create(name: '高屋 和子')
#Teacher.create(name: '鄭 小平')
#Teacher.create(name: '寺脇 拓')
#Teacher.create(name: '中村 健')
#Teacher.create(name: '中本 悟')
#Teacher.create(name: '野澤 健')
#Teacher.create(name: '野村 良一')
#Teacher.create(name: '橋本 貴彦')
#Teacher.create(name: '秦 劼')
#Teacher.create(name: '林 裕明')
#Teacher.create(name: 'PENG Virginia Mary')
#Teacher.create(name: 'FLATH DAVID')
#Teacher.create(name: '細貝 健司')
#Teacher.create(name: '堀 一三')
#Teacher.create(name: '松尾 匡')
#Teacher.create(name: '松本 朗')
#Teacher.create(name: '松本 睦')
#Teacher.create(name: '宮本 十至子')
#Teacher.create(name: '桃田 朗')
#Teacher.create(name: '山井 敏章')
#Teacher.create(name: '山本 信一')
#Teacher.create(name: 'LEE Kangkook')